### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by bengalih** [Raymai97/VMAudioBackHost#1]
Just wanted to say thank you!  This couldn't have been more timely.
I was trying to play some old multimedia educational discs that only ran on 32-bit XP and prior.
I'm running Windows 11 with VMWare Workstation 17.0.2 and I couldn't find any other fix that worked, including the version that ran on the guest.
This host based version started working immediately after clicking to start it.
Fantastic!

**Comment by Raymai97** [comment]
You're welcome. 😸 
I hope to receive more feedback from other people as well, to determine whether this solution really works well before I put more efforts on it, such as adding option to install background system service, to eliminate the need of clicking "Start" every time.
