### ISSUE TITLE
Works fine, thank you

### ISSUE THREAD

**Issue by freeidiot40x2** [Raymai97/VMAudioBackHost#2]
For no reason at all, the sound problems began once again in the Windows XP guest about a day ago. Now, appears to be resolved with this workaround. Thank you. 

Windows 10 version: 22 H2 (OS build 19045.3758)
VMWare Workstation version: 17.5.0 (Build 22583795). Will report back if any problems with sound is encountered again.

**Comment by Raymai97** [comment]
Glad to hear that. 👍
