### ISSUE TITLE
Works with W11 host with WSL2 (hyper-v) and XP Guest

### ISSUE THREAD

**Issue by fransking** [Raymai97/VMAudioBackHost#3]
W11 Host with WSL2 (hyper-v)
XP Guest
VMWare WorkStation Pro 17.5

Thank you!

**Comment by fransking** [comment]
And 98 Guest too

**Comment by Raymai97** [comment]
Glad to hear that. 👍

**Comment by hakatashi** [comment]
I tried many different avenues and finally this repository completely solved my problem. thank you!
